name 'docker_container'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures docker_container'
long_description 'Installs/Configures docker_container'
version '0.1.0'
