name 'docker_container'
maintainer 'Ryan Ovrevik'
maintainer_email 'rlo+github@ovrevik.com'
license 'MIT'
description 'Installs/Configures docker_container'
long_description 'Installs/Configures docker_container'
version '0.1.0'
